version: "3"
services:
    frontend:
        container_name: react-app
        build:
            context: ./frontend/schools
            dockerfile: Dockerfile
        
        ports:
            - "3000:3000"

    backend:
        container_name: node-web-app
        build:
            context: ./backend
            dockerfile: Dockerfile
   
        ports:
            - "5000:5000"
        